### ISSUE TITLE
Not hooking NtQuerySystemInformation function

### ISSUE THREAD

**Issue by BelodedAleksey** [NaniteFactory/gominhook#2]
I am trying to hook NtQuerySystemInformation from ntdll.dll. Doing it by example with MessageBox, but it is not working. Here is gist https://gist.github.com/BelodedAleksey/4d548e47e018571cb932ac4b76dee66f
Can you tell me please, what's wrong?

**Comment by NaniteFactory** [comment]
Your code is fine, and it did hooked the function `NtQuerySystemInformation` - also known as `ntdll!RtlGetNativeSystemInformation`.

Hook
![1_hook](https://user-images.githubusercontent.com/10949969/71642730-28b75500-2cf3-11ea-9a22-1e244db61319.PNG)

Unhook
![2_unhook](https://user-images.githubusercontent.com/10949969/71642731-2b19af00-2cf3-11ea-91ca-24553ef143ef.PNG)

Also you can call your function to test out if things are actually working.

```Go
var buf int32
proc.Call( // proc := syscall.NewLazyDLL("Ntdll.dll").NewProc("NtQuerySystemInformation")
	0x23, // SystemKernelDebuggerInformation
	uintptr(unsafe.Pointer(&buf)), // 4 bytes buffer
	4, // 4 bytes
	0, // NULL
)
```
