### ISSUE TITLE
Hook other process

### ISSUE THREAD

**Issue by apr3ndi5** [NaniteFactory/gominhook#3]
That's lib work to hook other process ?

**Comment by NaniteFactory** [comment]
Yes, as long as you can inject your code into another process's address space and then execute it in the context of the target process.

There are several techniques that allow you to do that. The following guide might help you.
https://www.codeproject.com/Articles/4610/Three-Ways-to-Inject-Your-Code-into-Another-Proces

I've hooked Windows 10's calculator with it.
https://github.com/NaniteFactory/hookwin10calc/blob/master/main.go
